'use client';
import {useLanguage} from '@/components/language';

import {useEffect,useState,useId,useRef} from 'react';
import Link from 'next/link';
import {Check,ArrowUpRight,LoaderCircle} from 'lucide-react';
import {services,type ServiceSlug} from '@/lib/content';
import {api,googleLogin,type User,type Availability} from '@/lib/client';
export function InterestForm({service}:{service?:ServiceSlug}){const {t,locale} = useLanguage();
  const id=useId(),[user,setUser]=useState<User|null>(null),[availability,setAvailability]=useState<Availability|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState('');
  const[name,setName]=useState(''),[email,setEmail]=useState(''),[privacy,setPrivacy]=useState(false),[marketing,setMarketing]=useState(false);
  const nameInput=useRef<HTMLInputElement>(null);
  useEffect(()=>{let live=true;Promise.all([api<{user:User|null}>('session').catch(()=>({user:null})),api<Availability>('config')]).then(([session,config])=>{if(!live)return;setAvailability(config);if(session.user){setUser(session.user);setEmail(session.user.email);}}).catch(()=>{if(live)setError('El registro no está disponible en este momento.');});return()=>{live=false;};},[]);
  async function login(){if(!privacy){setError('Lee y acepta el aviso de privacidad antes de continuar.');return;}setBusy(true);setError('');try{const u=await googleLogin();setUser(u);setEmail(u.email);nameInput.current?.focus();}catch(e){setError(e instanceof Error?e.message:t('No pudimos iniciar sesión.'));}finally{setBusy(false);}}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(name.trim().length<2){setError('Escribe tu nombre completo para continuar.');nameInput.current?.focus();return;}setBusy(true);setError('');const form=new FormData(event.currentTarget);try{
    const response=await api<{message:string}>('register',{name:name.trim(),email,locale,phone:form.get('phone')||'',message:form.get('message')||'',interests:service?[service]:form.getAll('interests'),kind:service?'inquiry':'waitlist',privacy,marketing,source:service||'home',website:form.get('website')||''});setResult(response.message);
  }catch(e){setError(e instanceof Error?e.message:t('No se pudo guardar.'));}finally{setBusy(false);}}
  return <div className="interest-panel"><div><p className="eyebrow">{service?t('HABLEMOS DE TU PROYECTO'):t('SÉ PARTE DEL COMIENZO')}</p><h2>{service?<>{t("Nos gustaría")}<br/>{' '}<em>{t("conocerte.")}</em></>:<>{t("Tu invitación")}<br/>{' '}<em>{t("a lo que viene.")}</em></>}</h2><p>{service?t('Déjanos tus datos y cuéntanos qué necesitas. Registraremos tu solicitud para darle seguimiento.'):t('Conoce primero nuestros servicios y las novedades de VIICASA.')}</p><p className="form-note">{service?t('Los servicios están en preparación. Esta solicitud no es una reserva ni genera un cobro.'):t('Sin compromisos. Puedes dejar de recibir novedades cuando quieras.')}</p></div>
    <div className="form-content">{result?<div className="success-panel" role="status"><Check size={30}/><h3>{t("Un buen comienzo.")}</h3><p>{t(result)}</p><button className="text-link" onClick={()=>setResult('')}>{t("Volver al formulario")}</button></div>:<form onSubmit={submit} className="interest-form">
      {availability?.mode==='emulator'&&<p className="notice">{t("Prueba local: utiliza únicamente datos ficticios. Estos registros no llegan a VIICASA.")}</p>}
      {user?<div className="signed-in"><Check size={16}/><span>{t("Conectado como ")}{user.email}</span></div>:<div className="email-registration-intro"><h3>{t('Regístrate con tu correo')}</h3><p>{t('Deja tu nombre y correo para registrar tu interés. No necesitas Google, contraseña ni confirmar un correo.')}</p></div>}
      <div className="field-grid"><label htmlFor={`${id}-name`}>{t("Nombre completo")}<input ref={nameInput} id={`${id}-name`} name="name" autoComplete="name" required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)} placeholder={t("Tu nombre")} aria-describedby={user?`${id}-google-help`:undefined}/></label><label htmlFor={`${id}-email`}>{t("Correo electrónico")}<input id={`${id}-email`} name="email" type="email" autoComplete="email" required maxLength={254} value={email} readOnly={!!user} onChange={e=>setEmail(e.target.value)} placeholder={t("nombre@correo.com")}/></label></div>
      {user&&<p id={`${id}-google-help`} className="form-note">{t('Tu correo de Google ya está verificado. Escribe tu nombre completo y envía el formulario para registrar tu interés.')}</p>}
      {!service&&<fieldset><legend>{t("¿Qué te gustaría descubrir?")}</legend><div className="interest-options">{services.map(s=><label key={s.slug}><input type="checkbox" name="interests" value={s.slug}/><span>{s.name}</span></label>)}</div></fieldset>}
      {service&&<><label htmlFor={`${id}-phone`}>{t("Teléfono ")}<span className="optional">{t("(opcional)")}</span><input id={`${id}-phone`} name="phone" type="tel" autoComplete="tel" maxLength={30}/></label><label htmlFor={`${id}-message`}>{t("Cuéntanos sobre tu proyecto ")}<span className="optional">{t("(opcional)")}</span><textarea id={`${id}-message`} name="message" rows={3} maxLength={2000}/></label></>}
      <div className="honeypot" aria-hidden="true"><label>{t("Sitio web")}<input name="website" tabIndex={-1} autoComplete="off"/></label></div>
      <label className="check-label"><input type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)} required/><span>{t("He leído y acepto el ")}<Link href="/privacidad" target="_blank" rel="noopener noreferrer">{t("aviso de privacidad")}</Link>.</span></label>
      <label className="check-label"><input type="checkbox" checked={marketing} onChange={e=>setMarketing(e.target.checked)} required={!service}/><span>{t("Quiero recibir novedades y el aviso de lanzamiento de VIICASA.")}{service?t(' (Opcional)'):''}</span></label>
      {availability&&!availability.google&&!availability.email&&<p className="notice">{t("El registro está en preparación. Todavía no estamos recibiendo datos.")}</p>}

      <button className="button submit-button" type="submit" disabled={busy||!(user?availability?.google:availability?.email)}>{busy?<LoaderCircle size={18} className="spin"/>:service?t('Enviar solicitud'):t('Unirme a la lista')}{!busy&&<ArrowUpRight size={18}/>}</button>
      {!user&&availability?.email&&<p className="form-note">{t("Revisa que tu correo esté bien escrito. Tus datos se guardarán al enviar el formulario.")}</p>}
      {!user&&<details className="optional-google"><summary>{t('Prefiero usar Google (opcional)')}</summary><p>{t('Google completará tu correo automáticamente. Tú escribes tu nombre y envías el formulario para registrar tu interés.')}</p><button type="button" className="button outline-button google-button" onClick={login} disabled={busy||!availability?.google}><span className="google-letter" aria-hidden="true">G</span>{t('Continuar con Google')}</button></details>}
    </form>}{error&&<p className="error-message" role="alert">{t(error)}</p>}</div></div>;
}
